services:
  app:
    image: sooyen/fast_pass:latest
    restart: always
    ports:
      - '9209:9209'
    # deploy:
    #   replicas: 1
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - PORT=3000
      - BASE_URL=${BASE_URL}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
      - REFRESH_EXPIRES_DAYS=${REFRESH_EXPIRES_DAYS}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_CLUSTER_MODE=true
      - REDIS_USE_TLS=true
      - REDIS_POOL_SIZE=${REDIS_POOL_SIZE:-20}
      - DB_POOL_SIZE=${DB_POOL_SIZE:-5}
      # - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      # - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - MONGO_URI=${MONGO_URI}
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://${MONITORING_HOST:-localhost}:4318
      - OTEL_SERVICE_NAME=fast_pass
      - ENABLE_TRACING=${ENABLE_TRACING}

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '3000:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
